FROM php:7.1

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        unzip \
	&& rm -r /var/lib/apt/lists/* \
	&& cd /root/ \
    && curl -sS https://getcomposer.org/installer | php \
    && ln -s /root/composer.phar /usr/local/bin/composer

RUN pecl channel-update pecl.php.net \
	&& pecl config-set php_ini /usr/local/etc/php.ini \
	&& pecl install xdebug \
	&& docker-php-ext-enable xdebug

WORKDIR /code

COPY . /code/

RUN composer install --no-interaction
